FROM maven:3.8.6-openjdk-17 AS build

WORKDIR /pro

COPY pom.xml ./
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /pro

COPY --from=build /app/target/product-0.0.1-SNAPSHOT.jar /app/product.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/product.jar"]
